version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: Dependencies
          command: ./gradlew dependencies
      - run:
          name: Sonarqube
          command: ./gradlew sonarqube -Dsonar.projectName=KotlinCircleCiSonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ziglee-github -Dsonar.login=37d89581af2b5b8e4a4ba5d997f8249515482182 -Dsonar.branch=master
